# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180131_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='no-img.jpg', upload_to='profile/picture/'),
        ),
    ]
