# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_auto_20180128_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=255)),
                ('notice_description', models.TextField()),
                ('notice_from', models.CharField(max_length=200)),
                ('notice_create', models.DateTimeField(auto_now_add=True)),
                ('notice_updated', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.School')),
            ],
        ),
    ]
