# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AvailableUser'),
        ),
    ]
