# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20180201_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=222),
            preserve_default=False,
        ),
    ]
