# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20180129_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
