# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20180130_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_from',
            field=models.CharField(max_length=200),
        ),
    ]
