# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0002_exam_exam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
