# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0004_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='result',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='result_GPA',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
