# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0005_auto_20180203_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AvailableUser'),
        ),
    ]
